version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wghtTrk-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: wghtTrk-nginx
    restart: always
    ports:
      - 500:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: wghtTrk-db
    image: keinos/sqlite3:latest
    volumes:
      - ../storage:/workspace

